name: Validate JSON

on:
  pull_request:
    paths:
      - 'config.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate config.json
        run: jq . config.json
